version: '2'
services:
  processmining-app:
    image: processmining
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://processmining-postgresql:5432/processmining
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  processmining-postgresql:
    extends:
      file: postgresql.yml
      service: processmining-postgresql
